package {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.entity;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.buyou.domain.framework.Command;
import com.buyou.domain.framework.CommandResult;

/**
 * Generated by code
 *
 * @author evan
 */
@TableName("jy_{{cookiecutter.name}}")
@Data
@ToString
public class {{cookiecutter.name|capitalize}} {

  private static final Logger logger = LoggerFactory.getLogger({{cookiecutter.name|capitalize}}.class);

  /** 数据库自动生成ID */
  @TableId(type = IdType.AUTO)
  private int id;

  /** 业务赋予ID */
  private Long {{cookiecutter.name}}Id;

  /** 名字 */
  private String name;

  /** Change it */
  public void working() {}

  /** Change it */
  public void working(Command command) {}

  /** Change it */
  public CommandResult working0(Command command) {
    return null;
  }

}
