package {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.entity;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.buyou.domain.framework.Command;
import com.buyou.domain.framework.CommandResult;

/**
 * Generated by code
 *
 * @author evan
 */
class {{cookiecutter.name|capitalize}}Test {
}
