package {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.service;

import {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.entity.{{cookiecutter.name|capitalize}};
import {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.repository.{{cookiecutter.name|capitalize}}Repository;
import com.buyou.domain.framework.AbstractEntityLifecycle;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by code
 *
 * @author evan
 */
public class {{cookiecutter.name|capitalize}}Lifecycle extends AbstractEntityLifecycle<Long, {{cookiecutter.name|capitalize}}> {

    public {{cookiecutter.name|capitalize}}Lifecycle({{cookiecutter.name|capitalize}}Repository {{cookiecutter.name}}Repository) {
        super({{cookiecutter.name}}Repository);
    }
}
