package {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.service;

import {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.entity.{{cookiecutter.name|capitalize}};
import {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.repository.{{cookiecutter.name|capitalize}}Repository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Generated by code
 *
 * @author evan
 */
public class {{cookiecutter.name|capitalize}}EventDomainService {

    private static final Logger logger = LoggerFactory.getLogger({{cookiecutter.name|capitalize}}DomainService.class);
    
    public {{cookiecutter.name|capitalize}}EventDomainService() {
    }

}
