package {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.repository;

import {{cookiecutter.pkg}}.{{cookiecutter.name}}.domain.entity.{{cookiecutter.name|capitalize}};
import com.buyou.domain.framework.EntityRepository;

/**
 * Generated by code
 *
 * @author evan
 */
public interface {{cookiecutter.name|capitalize}}Repository extends EntityRepository<Long, {{cookiecutter.name|capitalize}}> {}